# Generated by Django 4.2 on 2023-06-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Type_of_Doctor_you_want_to_consult',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Neurologist', 'Neurologist'), ('Oncologist', 'Oncologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Radiologist', 'Radiologist'), ('Surgeon', 'Surgeon'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Ophthalmologist', 'Ophthalmologist'), ('ENT Specialist', 'ENT Specialist'), ('Urologist', 'Urologist'), ('Nephrologist', 'Nephrologist'), ('Pulmonologist', 'Pulmonologist'), ('Allergist/Immunologist', 'Allergist/Immunologist'), ('Rheumatologist', 'Rheumatologist'), ('Hematologist', 'Hematologist'), ('Osteopath', 'Osteopath'), ('Chiropractor', 'Chiropractor'), ('Homeopath', 'Homeopath'), ('Ayurvedic Doctor', 'Ayurvedic Doctor'), ('Naturopath', 'Naturopath'), ('Physiotherapist', 'Physiotherapist'), ('Dentist', 'Dentist'), ('Veterinarian', 'Veterinarian')], default='Select', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.register_table'),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='Type_of_Doctor',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Neurologist', 'Neurologist'), ('Oncologist', 'Oncologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Radiologist', 'Radiologist'), ('Surgeon', 'Surgeon'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Ophthalmologist', 'Ophthalmologist'), ('ENT Specialist', 'ENT Specialist'), ('Urologist', 'Urologist'), ('Nephrologist', 'Nephrologist'), ('Pulmonologist', 'Pulmonologist'), ('Allergist/Immunologist', 'Allergist/Immunologist'), ('Rheumatologist', 'Rheumatologist'), ('Hematologist', 'Hematologist'), ('Osteopath', 'Osteopath'), ('Chiropractor', 'Chiropractor'), ('Homeopath', 'Homeopath'), ('Ayurvedic Doctor', 'Ayurvedic Doctor'), ('Naturopath', 'Naturopath'), ('Physiotherapist', 'Physiotherapist'), ('Dentist', 'Dentist'), ('Veterinarian', 'Veterinarian')], max_length=250),
        ),
    ]
