# Generated by Django 4.2 on 2023-06-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
