# Generated by Django 4.2 on 2023-06-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatMessage', '0003_message_profile_alter_thread_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
    ]
